#!/usr/bin/env python3.10
# Shebang for linux
from pathlib import Path

from coordinates import get_gps_coordinates
from exceptions import CantWriteHistory
from history import save_weather, PlainFileWeatherStorage
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    coordinates = get_gps_coordinates()
    weather = get_weather(coordinates)
    try:
        save_weather(weather, PlainFileWeatherStorage(Path.cwd() / 'history.txt'))
    except CantWriteHistory:
        print("The program somehow couldn't save history")
    print(format_weather(weather))


if __name__ == '__main__':
    main()
